# Blimp unique ID
id_num: 2

# sensor board parameters
my_ip: "192.168.0.101"
pi_ip: "192.168.0.52"

im_rows: 240
im_cols: 360
fps: 15
qual: 15

# motor board parameters
positive_only: True
k_r:  [0.45, 0., -1.7]
k_p:  [0.45, 0., -1.7]
k_yw: [0.002, 0.001, 0.07]
k_pz: [0.35, 0.001, 0.055]

