# Blimp unique ID
id_num: 1

# sensor board parameters
my_ip: "192.168.0.101"
pi_ip: "192.168.0.51"

im_rows: 240
im_cols: 360
fps: 15
qual: 15

# motor board parameters
positive_only: True
k_r:  [0.27, 0., -1.6]
k_p:  [0.27, 0., -1.6]
k_yw: [0.002, 0.001, 0.07]
k_pz: [0.29, 0.001, 0.045]

